import { Router } from "express";
import { auth } from "@/src/lib/auth/auth";
import { toNodeHandler } from "better-auth/node";
const router = Router();

/**
 * 
 *  all Possible routes generated by router.use(toNodeHandler(auth)):
	POST /api/v1/auth/sign-up/email
	POST /api/v1/auth/sign-in
	POST /api/v1/auth/sign-out
	POST /api/v1/auth/refresh-session
	GET /api/v1/auth/session
	POST /api/v1/auth/change-password
	POST /api/v1/auth/forgot-password
	POST /api/v1/auth/reset-password
	POST /api/v1/auth/verify-email
	POST /api/v1/auth/resend-verification-email
	GET /api/v1/auth/callback/:provider
	POST /api/v1/auth/callback/:provider
	POST /api/v1/auth/link-account
	POST /api/v1/auth/unlink-account
	GET /api/v1/auth/list-accounts
 */
router.use(toNodeHandler(auth));
export default router;
